# # Workflow derived from https://github.com/r-lib/pkgdown/blob/main/.github/workflows/pkgdown.yaml
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      publish:
        description: "Publish Site (uncheck for a dry run)"
        type: boolean
        required: false
        default: true

name: pkgdown-pr-preview

jobs:
  pkgdown-pr-preview:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.fork == false
    runs-on: ubuntu-latest
    # Only restrict concurrency for non-PR jobs
    concurrency:
      group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      PUBLISH: ${{ github.event_name == 'push' || github.event_name == 'release' || (github.event_name == 'workflow_dispatch' && inputs.publish) }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v5

      - uses: r-lib/actions/setup-tinytex@6f6e5bc62fba3a704f74e7ad7ef7676c5c6a2590  #v2.11.4

      - uses: r-lib/actions/setup-pandoc@6f6e5bc62fba3a704f74e7ad7ef7676c5c6a2590  #v2.11.4

      - uses: r-lib/actions/setup-r@6f6e5bc62fba3a704f74e7ad7ef7676c5c6a2590  #v2.11.4
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@6f6e5bc62fba3a704f74e7ad7ef7676c5c6a2590  #v2.11.4
        with:
          extra-packages: any::pkgdown, local::.
          needs: website

      - name: Build site
        run: pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)
        shell: Rscript {0}

      - name: Deploy production to GitHub pages ðŸš€
        if: contains(env.PUBLISH, 'true')
        uses: JamesIves/github-pages-deploy-action@6c2d9db40f9296374acc17b90404b6e8864128c8  #v4.7.3
        with:
          clean: false
          branch: gh-pages
          folder: docs
      - id: deploy-dir 
        name: Determine dev status
        run: |
          if [[ $(grep -c -E 'sion. ([0-9]*\.){3}' ${{ github.workspace }}/DESCRIPTION) == 1 ]]; then
            echo 'dir=./docs/dev' >> $GITHUB_OUTPUT
          else
            echo 'dir=./docs' >> $GITHUB_OUTPUT
          fi
      - name: Deploy PR preview to Netlify
        if: contains(env.PUBLISH, 'false')
        id: netlify-deploy
        uses: nwtgck/actions-netlify@4cbaf4c08f1a7bfa537d6113472ef4424e4eb654  #v3.0.0
        with:
          publish-dir: '${{ steps.deploy-dir.outputs.dir }}'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message:
            'Deploy from GHA: ${{ github.event.pull_request.title || github.event.head_commit.message }} (${{ github.sha }})'
          enable-pull-request-comment: true
          enable-commit-comment: false
          enable-commit-status: false
          enable-github-deployment: false
          overwrites-pull-request-comment: true
          fails-without-credentials: true

        timeout-minutes: 1
