name: Hub Config Validation (R)

on:
  workflow_dispatch:
  pull_request:
    branches: main
    paths:
      - 'inst/testhubs/v5/target_dir/hub-config/**'
      - '!inst/testhubs/v5/target_dir/**README**'

permissions:
  contents: read
  pull-requests: write

jobs:
  validate-hub-config:
    runs-on: ubuntu-22.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      PR_NUMBER: ${{ github.event.number }}
      HUB_PATH: "inst/testhubs/v5/target_dir"

    steps:
      - uses: actions/checkout@v5

      - uses: r-lib/actions/setup-r@6f6e5bc62fba3a704f74e7ad7ef7676c5c6a2590  #v2.11.4
        with:
          install-r: false
          use-public-rspm: true
          extra-repositories: 'https://hubverse-org.r-universe.dev'

      - name: Update R
        run: |
          sudo apt-get update

      - uses: r-lib/actions/setup-r-dependencies@6f6e5bc62fba3a704f74e7ad7ef7676c5c6a2590  #v2.11.4
        with:
          cache: 'always'
          packages: |
            any::hubAdmin
            any::sessioninfo

      - name: Run validations
        id: validate
        run: |
          hub_path <- Sys.getenv("HUB_PATH")
          diff <- file.path(hub_path, "diff.md")
          output <- Sys.getenv("GITHUB_OUTPUT")
          timestamp <- function(outfile) {
            stamp <- format(Sys.time(), usetz = TRUE, tz = "UTC")
            cat(stamp, "\n", file = outfile, sep = "", append = TRUE)
          }
          v <- hubAdmin::validate_hub_config(
            hub_path = hub_path
          )
          # check if there were any failures
          invalid <- any(vapply(v, isFALSE, logical(1)))
          if (invalid) {
            cat("result=false", "\n", file = output, sep = "", append = TRUE)
            # write output to HTML
            tbl <- hubAdmin::view_config_val_errors(v)
            writeLines("## :x: Invalid Configuration\n", diff)
            cat("\nErrors were detected in one or more config files in `hub-config/`. Details about the exact locations of the errors can be found in the table below.\n", file = diff, append = TRUE)
            cat(gt::as_raw_html(tbl), "\n", file = diff, sep = "", append = TRUE)
            timestamp(diff)
          } else {
            cat("result=true", "\n", file = output, sep = "", append = TRUE)
            writeLines(":white_check_mark: Hub correctly configured!\n", diff)
            timestamp(diff)
          }
        shell: Rscript {0}
      - name: "Comment on PR"
        id: comment-diff
        if: ${{ github.event_name != 'workflow_dispatch' }}
        uses: carpentries/actions/comment-diff@083bb9952b1414bd2b9e10ecec1717c938aba4c5 #v0.17.0
        with:
          pr: ${{ env.PR_NUMBER }}
          path: ${{ env.HUB_PATH }}/diff.md
      - name: Error on Failure
        if: ${{ steps.validate.outputs.result == 'false' }}
        run: |
          echo "::error title=Invalid Configuration::Errors were detected in one or more config files in 'hub-config/'"
          exit 1

